# -*- encoding: utf-8 -*-
# This file generated automatically using vocab-fetch from http://w3c.github.io/csvw/ns/csvw.ttl
require 'rdf'
module RDF::Tabular
  class CSVW < RDF::StrictVocabulary("http://www.w3.org/ns/csvw#")

    # Class definitions
    term :Column,
      comment: %(A Column Description describes a single column.).freeze,
      label: "Column Description".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdfs:Class".freeze
    term :Datatype,
      comment: %(Describes facets of a datatype.).freeze,
      label: "Datatype".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdfs:Class".freeze
    term :Dialect,
      comment: %(A Dialect Description provides hints to parsers about how to parse a linked file.).freeze,
      label: "Dialect Description".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdfs:Class".freeze
    term :Direction,
      comment: %(The class of table/text directions.).freeze,
      label: "Direction".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdfs:Class".freeze
    term :Schema,
      comment: %(A Schema is a definition of a tabular format that may be common to multiple tables.).freeze,
      label: "Schema".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdfs:Class".freeze
    term :Table,
      comment: %(A Table describes an Annotated Table.).freeze,
      label: "Table Description".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdfs:Class".freeze
    term :TableGroup,
      comment: %(A Table Group describes an Annotated Table Group.).freeze,
      label: "Table Group Description".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdfs:Class".freeze
    term :Transformation,
      comment: %(A Transformation Definition is a definition of how tabular data can be transformed into another format.).freeze,
      label: "Transformation Definition".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdfs:Class".freeze

    # Property definitions
    property :aboutUrl,
      comment: %(A URI template property that may be used to create a unique identifier for each cell within a row when mapping data to other formats).freeze,
      label: "about URL".freeze,
      range: "http://www.w3.org/ns/csvw#uriTemplate".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :base,
      comment: %(An atomic property that contains a single string: a term defined in the default context representing a built-in datatype URL).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "base".freeze,
      range: "rdfs:Datatype".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :columns,
      comment: %(An array of Column Descriptions.).freeze,
      domain: "http://www.w3.org/ns/csvw#Schema".freeze,
      label: "columns".freeze,
      range: "http://www.w3.org/ns/csvw#Column".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :commentPrefix,
      comment: %(A character that, when it appears at the beginning of a skipped row, indicates a comment that should be associated as a comment annotation to the table. The default is "#".).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "comment prefix".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :datatype,
      comment: %(An object property that contains either a single string that is the main datatype of the values of the cell or a datatype description object.).freeze,
      label: "datatype".freeze,
      range: "http://www.w3.org/ns/csvw#Datatype".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :decimalChar,
      comment: %(A single character string whose value is used to represent a decimal point within the number. The default value is ".".).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "decimal character".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :default,
      comment: %(An atomic property holding a single string that provides a default string value for the cell in cases where the original string value is a null value. This default value may be used when converting the table into other formats.).freeze,
      label: "default".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :delimiter,
      comment: %(The separator between cells. The default is ",".).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "delimiter".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :dialect,
      comment: %(Provides hints to processors about how to parse the referenced files for to create tabular data models for an individual table, or all the tables in a group.).freeze,
      label: "dialect".freeze,
      range: "http://www.w3.org/ns/csvw#Dialect".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :doubleQuote,
      comment: %(If true, sets the escape character flag to ". If false, to \.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "double quote".freeze,
      range: "xsd:boolean".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :encoding,
      comment: %(The character encoding for the file, one of the encodings listed in [encoding]. The default is utf-8.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "encoding".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :foreignKeys,
      comment: %(An array of foreign key definitions that define how the values from specified columns within this table link to rows within this table or other tables.).freeze,
      domain: "http://www.w3.org/ns/csvw#Schema".freeze,
      label: "foreign keys".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :format,
      comment: %(A definition of the format of the cell, used when parsing the cell.).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "format".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :groupChar,
      comment: %(A single character string whose value is used to group digits within the number. The default value is ",".).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "group character".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :header,
      comment: %(A single boolean atomic property that, if true, sets the header row count flag to 1, and if false to 0, unless headerRowCount is provided, in which case the value provided for the header property is ignored.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "header".freeze,
      range: "xsd:boolean".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :headerColumnCount,
      comment: %(The number of header columns \(following the skipped columns\) in each row. The default is 0.
).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "header column count".freeze,
      range: "xsd:nonNegativeInteger".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :headerRowCount,
      comment: %(The number of header rows \(following the skipped rows\) in the file. The default is 1.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "header row count".freeze,
      range: "xsd:nonNegativeInteger".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :language,
      comment: %(A language code as defined by [BCP47]. Indicates the language of the value within the cell.).freeze,
      label: "language".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :length,
      comment: %(The exact length of the value of the cell.).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "length".freeze,
      range: "xsd:nonNegativeInteger".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :lineTerminator,
      comment: %(The character that is used at the end of a row. The default is CRLF.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "line terminator".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :maxExclusive,
      comment: %(The maximum value for the cell \(exclusive\).).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "max exclusive".freeze,
      range: "xsd:integer".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :maxInclusive,
      comment: %(The maximum value for the cell \(inclusive\). ).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "max inclusive".freeze,
      range: "xsd:integer".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :maxLength,
      comment: %(The maximum length of the value of the cell.).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "max length".freeze,
      range: "xsd:nonNegativeInteger".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :minExclusive,
      comment: %(The minimum value for the cell \(exclusive\).).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "min exclusive".freeze,
      range: "xsd:integer".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :minInclusive,
      comment: %(The minimum value for the cell \(inclusive\).).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "min inclusive".freeze,
      range: "xsd:integer".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :minLength,
      comment: %(The minimum length of the value of the cell.).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "min length".freeze,
      range: "xsd:nonNegativeInteger".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :name,
      comment: %(An atomic property that gives a canonical name for the column. This must be a string. Conversion specifications must use this property as the basis for the names of properties/elements/attributes in the results of conversions.).freeze,
      domain: "http://www.w3.org/ns/csvw#Column".freeze,
      label: "name".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :notes,
      comment: %(An array of objects representing annotations. This specification does not place any constraints on the structure of these objects.).freeze,
      domain: "http://www.w3.org/ns/csvw#Table".freeze,
      label: "notes".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :null,
      comment: %(The string used for null values. If not specified, the default for this is the empty string.).freeze,
      label: "null".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :ordered,
      comment: %(Indicates if multiple values of a cell are considered ordered or unordered; see separator.).freeze,
      label: "ordered".freeze,
      range: "xsd:boolean".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :pattern,
      comment: %(A regular expression string, in the syntax and interpreted as defined by [ECMASCRIPT].).freeze,
      domain: "http://www.w3.org/ns/csvw#Datatype".freeze,
      label: "pattern".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :primaryKey,
      comment: %(A column reference property that holds either a single reference to a column description object or an array of references.).freeze,
      domain: "http://www.w3.org/ns/csvw#Schema".freeze,
      label: "primary key".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :propertyUrl,
      comment: %(An URI template property that holds one or more strings that may be expanded to URIs for properties if the table is mapped to another format. The default value of propertyUrl is "{#_name}".).freeze,
      label: "property URL".freeze,
      range: "http://www.w3.org/ns/csvw#uriTemplate".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :quoteChar,
      comment: %(The character that is used around escaped cells.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "quote char".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :required,
      comment: %(A boolean value which indicates whether every cell within the column must have a non-null value.).freeze,
      domain: "http://www.w3.org/ns/csvw#Column".freeze,
      label: "required".freeze,
      range: "xsd:boolean".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :resources,
      comment: %(An array of table descriptions for the tables in the group.).freeze,
      domain: "http://www.w3.org/ns/csvw#TableGroup".freeze,
      label: "resources".freeze,
      range: "http://www.w3.org/ns/csvw#Table".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :row,
      comment: %(Relates a Table to each Row output.).freeze,
      domain: "http://www.w3.org/ns/csvw#Table".freeze,
      label: "row".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      subPropertyOf: "rdfs:member".freeze,
      type: "rdf:Property".freeze
    property :rownum,
      comment: %(The position of the row amongst the rows of the Annotated Tabl, starting from 1 ).freeze,
      label: "row number".freeze,
      range: "xsd:integer".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :scriptFormat,
      comment: %(A link property giving the single URL for the format that is used by the script or template. If one has been defined, this should be a URL for a media type, in the form http://www.iana.org/assignments/media-types/media-type such as http://www.iana.org/assignments/media-types/application/javascript. Otherwise, it can be any URL that describes the script or template format.).freeze,
      domain: "http://www.w3.org/ns/csvw#Transformation".freeze,
      label: "script format".freeze,
      range: "xsd:anyURI".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :separator,
      comment: %(The character used to separate items in the string value of the cell.).freeze,
      label: "separator".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :skipBlankRows,
      comment: %(Indicates whether to ignore wholly empty rows \(ie rows in which all the cells are empty\). The default is false.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "skip blank rows".freeze,
      range: "xsd:boolean".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :skipColumns,
      comment: %(The number of columns to skip at the beginning of each row, before any header columns. The default is 0.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "skip columns".freeze,
      range: "xsd:nonNegativeInteger".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :skipInitialSpace,
      comment: %(If true, sets the trim flag to "start". If false, to false.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "skip initial space".freeze,
      range: "xsd:boolean".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :skipRows,
      comment: %(The number of rows to skip at the beginning of the file, before a header row or tabular data.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "skip rows".freeze,
      range: "xsd:nonNegativeInteger".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :source,
      comment: %(The format to which the tabular data should be transformed prior to the transformation using the template. If the value is "json", the tabular data should first be transformed first to JSON based on the simple mapping defined in Generating JSON from Tabular Data on the Web. If the value is "rdf", it should similarly first be transformed to XML based on the simple mapping defined in Generating RDF from Tabular Data on the Web.).freeze,
      domain: "http://www.w3.org/ns/csvw#Transformation".freeze,
      label: "source".freeze,
      range: "xsd:string".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :suppressOutput,
      comment: %(A boolean atomic property. If true, suppresses any output that would be generated when converting a table or cells within a column.).freeze,
      label: "suppress output".freeze,
      range: "xsd:boolean".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :table,
      comment: %(Relates an Table group to annotated tables. \(Note, this is different from csvw:resources, which relates metadata, rather than resulting annotated table descriptions.).freeze,
      domain: "http://www.w3.org/ns/csvw#TableGroup".freeze,
      label: "table".freeze,
      range: "http://www.w3.org/ns/csvw#Table".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      subPropertyOf: "rdfs:member".freeze,
      type: "rdf:Property".freeze
    property :tableDirection,
      comment: %(One of csvw:rtl csvw:ltr or csvw:default. Indicates whether the tables in the group should be displayed with the first column on the right, on the left, or based on the first character in the table that has a specific direction. ).freeze,
      label: "table direction".freeze,
      range: "http://www.w3.org/ns/csvw#Direction".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :tableSchema,
      comment: %(An object property that provides a schema description for an individual table, or all the tables in a group.).freeze,
      label: "table schema".freeze,
      range: "http://www.w3.org/ns/csvw#Schema".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :targetFormat,
      comment: %(A link property giving the single URL for the format that will be created through the transformation. If one has been defined, this should be a URL for a media type, in the form http://www.iana.org/assignments/media-types/media-type such as http://www.iana.org/assignments/media-types/text/calendar. Otherwise, it can be any URL that describes the target format.).freeze,
      domain: "http://www.w3.org/ns/csvw#Transformation".freeze,
      label: "target format".freeze,
      range: "xsd:anyURI".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :textDirection,
      comment: %(One of csvw:rtl or csvw:ltr. Indicates whether the text within cells should be displayed by default as left-to-right or right-to-left text. ).freeze,
      label: "text direction".freeze,
      range: "http://www.w3.org/ns/csvw#Direction".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :title,
      comment: %(For a Transformation A natural language property that describes the format that will be generated from the transformation. This is useful if the target format is a generic format \(such as application/json\) and the transformation is creating a specific profile of that format.

For a Column: A natural language property that provides possible alternative names for the column.).freeze,
      label: "title".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :transformations,
      comment: %(An array property of transformation definitions that provide mechanisms to transform the tabular data into other formats.).freeze,
      label: "transformations".freeze,
      range: "http://www.w3.org/ns/csvw#Transformation".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :trim,
      comment: %(Indicates whether to trim whitespace around cells; may be true, false, start or end. The default is false.).freeze,
      domain: "http://www.w3.org/ns/csvw#Dialect".freeze,
      label: "trim".freeze,
      range: "xsd:boolean".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :url,
      comment: %(For a Table: This link property gives the single URL of the CSV file that the table is held in, relative to the location of the metadata document.

For a Template: A link property giving the single URL of the file that the template is held in, relative to the location of the metadata document.).freeze,
      label: "url".freeze,
      range: "xsd:anyURI".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :valueUrl,
      comment: %(An URI template property that is used to define one or more resources value of a cell instead of a literal values.).freeze,
      label: "valueUrl".freeze,
      range: "http://www.w3.org/ns/csvw#uriTemplate".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze
    property :virtual,
      comment: %(A boolean atomic property taking a single value which indicates whether the column is a virtual column not present in the original source).freeze,
      domain: "http://www.w3.org/ns/csvw#Column".freeze,
      label: "virtual".freeze,
      range: "xsd:boolean".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "rdf:Property".freeze

    # Datatype definitions
    term :JSON,
      comment: %(A literal containing JSON.).freeze,
      label: "JSON".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      subClassOf: "xsd:string".freeze,
      type: "rdfs:Datatype".freeze
    term :uriTemplate,
      comment: %().freeze,
      label: "uri template".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      subClassOf: "xsd:anyURI".freeze,
      type: "rdfs:Datatype".freeze

    # Extra definitions
    term :"",
      "dc:description" => %(This document describes the RDFS vocabulary description used in the Metadata Vocabulary for Tabular Data [[tabular-metadata]] along with the default JSON-LD Context.).freeze,
      "dc:title" => %(CSVW Namespace Vocabulary Terms).freeze,
      label: "".freeze,
      type: "owl:Ontology".freeze
    term :csvEncodedTabularData,
      comment: %(Describes the role of a CSV file in the tabular data mapping.).freeze,
      label: "CSV Encoded Tabular Data".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "prov:Role".freeze
    term :ltr,
      comment: %(Indicates text should be processed left to right.).freeze,
      label: "left to right".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "http://www.w3.org/ns/csvw#Direction".freeze
    term :rtl,
      comment: %(Indiects text should be processed right to left).freeze,
      label: "right to left".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "http://www.w3.org/ns/csvw#Direction".freeze
    term :tabularMetadata,
      comment: %(Describes the role of a Metadata file in the tabular data mapping.).freeze,
      label: "Tabular Metadata".freeze,
      "rdfs:isDefinedBy" => %(http://www.w3.org/ns/csvw#).freeze,
      type: "prov:Role".freeze
  end
end
